### ISSUE TITLE
release playground

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/ddr#9]
attempts to release the project (not to spam in other issues)

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@yegor256 can you please help, I tried to trigger javadoc creation by creating dummy java class, but I still get this mistake:
```
[ERROR]   Rule "javadoc-staging" failures
[ERROR]     * Missing: no javadoc jar found in folder '/org/eolang/ddr/0.0.1'
```

You can see the full log above

**Comment by yegor256** [comment]
@OlesiaSub I think, that the problem is here: https://github.com/objectionary/ddr/blob/master/pom.xml#L105 maven-javadoc-plugin is using this property in order to find `.java` files. Of course, it doesn't find anything there. In order to solve this, you should explicitly add `maven-javadoc-plugin` configuration section to `build/pluginManagement/plugins` part of `pom.xml` and set the location of `.java` files, using `sourcepath`: https://stackoverflow.com/questions/1195647/maven-javadoc-plugin-how-can-i-include-only-certain-classes

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@yegor256 thank you!!
